// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAJi2KdDEN_CU68xOvQiXS9qZdgfWegWk',
    appId: '1:771589493730:web:1a58e511d1c7e289279fbb',
    messagingSenderId: '771589493730',
    projectId: 'testing-7f712',
    authDomain: 'testing-7f712.firebaseapp.com',
    storageBucket: 'testing-7f712.firebasestorage.app',
    measurementId: 'G-J5ELHDWMDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu1SgMaVOktYAmBSkxxAqFs8cNrJtzPKg',
    appId: '1:771589493730:android:7d742263aa4d9095279fbb',
    messagingSenderId: '771589493730',
    projectId: 'testing-7f712',
    storageBucket: 'testing-7f712.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYRDBs6H_gxeeehIBDE5LtBnF40UjPAmU',
    appId: '1:771589493730:ios:b397c568ec88c32b279fbb',
    messagingSenderId: '771589493730',
    projectId: 'testing-7f712',
    storageBucket: 'testing-7f712.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYRDBs6H_gxeeehIBDE5LtBnF40UjPAmU',
    appId: '1:771589493730:ios:b397c568ec88c32b279fbb',
    messagingSenderId: '771589493730',
    projectId: 'testing-7f712',
    storageBucket: 'testing-7f712.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAJi2KdDEN_CU68xOvQiXS9qZdgfWegWk',
    appId: '1:771589493730:web:83ef17a4167d54bb279fbb',
    messagingSenderId: '771589493730',
    projectId: 'testing-7f712',
    authDomain: 'testing-7f712.firebaseapp.com',
    storageBucket: 'testing-7f712.firebasestorage.app',
    measurementId: 'G-FYM6BV4R2Q',
  );
}
